parameters:
    ezplatform.fieldtype.user-generated-content.identifier: 'ezugc'

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\UserGeneratedContent\FieldType\Type:
        autoconfigure: false
        autowire: true
        public: true
        parent: ezpublish.fieldType
        arguments:
            $fieldTypeIdentifier: '%ezplatform.fieldtype.user-generated-content.identifier%'
        tags:
            - { name: ezplatform.field_type, alias: '%ezplatform.fieldtype.user-generated-content.identifier%' }

    EzSystems\UserGeneratedContent\FieldType\Converter\UserGeneratedContentConverter:
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: '%ezplatform.fieldtype.user-generated-content.identifier%' }

    EzSystems\UserGeneratedContent\FieldType\Mapper\UserGeneratedContentFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.definition, fieldType: '%ezplatform.fieldtype.user-generated-content.identifier%' }
            - { name: ezplatform.field_type.form_mapper.value, fieldType: '%ezplatform.fieldtype.user-generated-content.identifier%' }

    EzSystems\UserGeneratedContent\Form\Type\ContentFormType: ~
